# Generated by Django 5.0.6 on 2024-05-16 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('disques', 'Records'), ('vetements', 'Clothing'), ('affiches', 'Posters'), ('divers', 'Miscellaneous')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1900), django.core.validators.MinValueValidator(2024)]),
            preserve_default=False,
        ),
    ]
