# Generated by Django 5.0.6 on 2024-05-16 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2024), django.core.validators.MinValueValidator(1900)]),
        ),
    ]
