# Generated by Django 5.0.6 on 2024-05-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='singer_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
